export const currentYear = new Date().getFullYear();
export const START_YEARS = Array.from({ length: 16 }, (_, i) =>
  (currentYear - 15 + i).toString(),
).reverse();
export const END_YEARS = Array.from({ length: 16 }, (_, i) =>
  (currentYear + i).toString(),
);

export const COUNTRIES = [
  "India",
  "United States of America",
  "United Kingdom",
  "Canada",
  "Australia",
  "Singapore",
  "Germany",
  "France",
  "United Arab Emirates",
  "Japan",
  "South Korea",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Austria",
  "Bahamas",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Egypt",
  "Estonia",
  "Fiji",
  "Finland",
  "Georgia",
  "Ghana",
  "Greece",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Lebanon",
  "Malaysia",
  "Maldives",
  "Mauritius",
  "Mexico",
  "Morocco",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
].sort();

export const INDIAN_STATES_UTS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const INSTITUTIONS = [
  // IITs
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT BHU (Varanasi)",
  "IIT (ISM) Varanasi",
  "IIT Patna",
  "IIT Bhubaneswar",
  "IIT Mandi",
  "IIT Ropar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Tirupati",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Palakkad",
  "IIT Dharwad",
  "IIT Jammu",
  // NITs
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Calicut",
  "NIT Rourkela",
  "MNIT Jaipur",
  "VNIT Nagpur",
  "NIT Kurukshetra",
  "NIT Allahabad",
  "NIT Durgapur",
  "NIT Silchar",
  "NIT Jalandhar",
  "NIT Meghalaya",
  "NIT Bhopal",
  "NIT Raipur",
  "NIT Agartala",
  "NIT Goa",
  "NIT Jamshedpur",
  "NIT Patna",
  "NIT Hamirpur",
  "NIT Puducherry",
  "NIT Uttarakhand",
  "NIT Delhi",
  "NIT Mizoram",
  "NIT Srinagar",
  // Jaipur / Rajasthan Locals
  "JECRC Foundation",
  "JECRC University",
  "MNIT Jaipur",
  "LNMIIT Jaipur",
  "Manipal University Jaipur (MUJ)",
  "Swami Keshavanand Institute of Technology (SKIT)",
  "Poornima College of Engineering",
  "Poornima Institute of Engineering & Technology",
  "Poornima University",
  "Amity University Jaipur",
  "Arya College of Engineering",
  "Vivekananda Global University (VGU)",
  "Rajasthan Technical University (RTU)",
  // Major Privates & Others
  "BITS Pilani (Pilani Campus)",
  "BITS Pilani (Goa Campus)",
  "BITS Pilani (Hyderabad Campus)",
  "BITS Pilani (Dubai Campus)",
  "VIT Vellore",
  "VIT Chennai",
  "SRM University (KTR)",
  "SRM University (Ramapuram)",
  "Manipal Academy of Higher Education (MAHE)",
  "Thapar Institute of Engineering and Technology",
  "Delhi Technological University (DTU)",
  "NSUT Delhi",
  "IIIT Hyderabad",
  "IIIT Delhi",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "Master's Union",
  "Scaler School of Technology",
  "Scaler School of Business",
].sort();

export const COURSES = [
  // Bachelors
  "B.Tech",
  "B.E.",
  "BCA",
  "B.Sc",
  "B.Sc (Hons)",
  "BBA",
  "B.Com",
  "B.Com (Hons)",
  "B.A.",
  "B.A. (Hons)",
  "B.Des",
  "B.Arch",
  "B.Pharm",
  "MBBS",
  "BDS",
  "BPT",
  "LLB",
  "BA LLB",
  "BBA LLB",
  "BHM",
  "B.Ed",
  // Masters
  "M.Tech",
  "M.E.",
  "MCA",
  "M.Sc",
  "MBA",
  "PGDM",
  "M.Com",
  "M.A.",
  "M.Des",
  "M.Arch",
  "M.Pharm",
  "MD",
  "MS",
  "LLM",
  // Others
  "Ph.D",
  "Diploma",
  "Advanced Diploma",
  "Certificate Course",
  "Bootcamp",
  "Self-Taught",
].sort();

export const SPECIALIZATIONS = [
  "Computer Science Engineering (CSE)",
  "Information Technology (IT)",
  "Artificial Intelligence & Machine Learning (AI/ML)",
  "Data Science",
  "Cyber Security",
  "Cloud Computing",
  "Software Engineering",
  "Electronics & Communication Engineering (ECE)",
  "Electrical Engineering (EE)",
  "Mechanical Engineering (ME)",
  "Civil Engineering (CE)",
  "Aerospace Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Robotics & Automation",
  "Finance",
  "Marketing",
  "Human Resources (HR)",
  "Operations Management",
  "International Business",
  "Business Analytics",
  "Entrepreneurship",
  "UI/UX Design",
  "Graphic Design",
  "Product Design",
  "Fashion Design",
  "Animation & VFX",
  "Filmmaking",
  "Journalism & Mass Communication",
  "Physics",
  "Chemistry",
  "Mathematics",
  "Economics",
  "Psychology",
  "English Literature",
  "Corporate Law",
  "Criminal Law",
  "General Medicine",
  "Surgery",
].sort();

export const COUNTRY_CODES = [
  "🇮🇳 +91",
  "🇺🇸 +1",
  "🇬🇧 +44",
  "🇨🇦 +1",
  "🇦🇺 +61",
  "🇸🇬 +65",
  "🇦🇪 +971",
].sort();

export const MACRO_DOMAINS = [
  "Engineering",
  "Design",
  "Filmmaking",
  "Business/Operations",
  "Marketing",
  "Sales",
  "Science",
  "Healthcare/Medical",
  "Arts/Humanities",
  "Legal",
  "Finance/Accounting",
  "Content Creation",
  "Education/Academia",
  "Architecture",
  "Government/Policy",
].sort();

export const MICRO_NICHES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "AI/ML Engineer",
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "DevOps Engineer",
  "Cloud Architect",
  "Blockchain Developer",
  "Cybersecurity Analyst",
  "Game Developer",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "3D Modeler",
  "Animator",
  "Director",
  "Producer",
  "Cinematographer",
  "Video Editor",
  "Screenwriter",
  "Actor",
  "Founder / CEO",
  "COO",
  "CTO",
  "Product Manager",
  "Project Manager",
  "Consultant",
  "Venture Capitalist",
  "Investment Banker",
  "Financial Analyst",
  "Accountant",
  "Growth Marketer",
  "Digital Marketer",
  "SEO Specialist",
  "Social Media Manager",
  "B2B Sales",
  "Account Executive",
  "Copywriter",
  "Journalist",
  "Public Relations",
  "Physician",
  "Surgeon",
  "Psychologist",
  "Researcher",
  "Professor",
  "Corporate Lawyer",
].sort();

export const RAW_SKILLS = [
  "Python",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Java",
  "C++",
  "C#",
  "C",
  "Go",
  "Rust",
  "Ruby",
  "Swift",
  "Kotlin",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "AWS",
  "Google Cloud (GCP)",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  "Git",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Computer Vision",
  "NLP",
  "Pandas",
  "Tableau",
  "PowerBI",
  "Blockchain",
  "Solidity",
  "Figma",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Adobe After Effects",
  "DaVinci Resolve",
  "Blender",
  "Unity",
  "Unreal Engine",
  "SEO",
  "SEM",
  "Google Analytics",
  "Facebook Ads",
  "Copywriting",
  "B2B Sales",
  "Cold Calling",
  "Public Speaking",
  "Financial Modeling",
  "Project Management",
  "Agile",
].sort();

export const LANGUAGES = [
  "English",
  "Hindi",
  "Mandarin Chinese",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Korean",
  "Persian",
];

export const CURRENT_STATUSES = [
  "School Student",
  "Undergraduate",
  "Postgraduate",
  "Working Professional",
  "Creator",
  "Freelancer",
  "Dropped Out",
  "Building the Passion",
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
