// src/pages/Auth/constants/taxonomy.js

export const currentYear = new Date().getFullYear();

export const START_YEARS = Array.from({ length: 16 }, (_, i) =>
  (currentYear - 15 + i).toString(),
).reverse();

export const END_YEARS = Array.from({ length: 16 }, (_, i) =>
  (currentYear + i).toString(),
);

export const COUNTRIES = [
  "India",
  "United States of America",
  "United Kingdom",
  "Canada",
  "Australia",
  "Singapore",
  "Germany",
  "France",
  "United Arab Emirates",
  "Japan",
  "South Korea",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Egypt",
  "Estonia",
  "Fiji",
  "Finland",
  "Georgia",
  "Ghana",
  "Greece",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Lebanon",
  "Malaysia",
  "Maldives",
  "Mauritius",
  "Mexico",
  "Morocco",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
].sort();

export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const INSTITUTIONS = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "BITS Pilani",
  "VIT Vellore",
  "SRM University",
  "Manipal University",
  "DTU Delhi",
  "NSUT Delhi",
  "IIIT Hyderabad",
  "IIIT Delhi",
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "NIT Calicut",
  "MNIT Jaipur",
  "JECRC Foundation",
  "JECRC University",
  "LNMIIT Jaipur",
  "Manipal University Jaipur",
  "Poornima College of Engineering",
  "Amity University",
  "Master's Union",
  "Scaler School of Technology",
].sort();

export const COURSES = [
  "B.Tech",
  "B.E.",
  "BCA",
  "B.Sc",
  "BBA",
  "B.Com",
  "B.A.",
  "B.Des",
  "B.Arch",
  "MBBS",
  "LLB",
  "M.Tech",
  "MCA",
  "M.Sc",
  "MBA",
  "PGDM",
  "M.Com",
  "MD",
  "Ph.D",
  "Diploma",
  "Bootcamp",
  "Self-Taught",
].sort();

export const SPECIALIZATIONS = [
  "Computer Science (CSE)",
  "Information Technology",
  "Artificial Intelligence & Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Software Engineering",
  "Electronics & Communication (ECE)",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Finance",
  "Marketing",
  "Human Resources",
  "Business Analytics",
  "UI/UX Design",
  "Graphic Design",
  "Product Design",
  "Physics",
  "Mathematics",
  "Economics",
  "Psychology",
  "Corporate Law",
  "General Medicine",
].sort();

export const MACRO_DOMAINS = [
  "Engineering",
  "Design",
  "Business / Operations",
  "Marketing",
  "Sales",
  "Science",
  "Healthcare",
  "Arts & Humanities",
  "Legal",
  "Finance & Accounting",
  "Content Creation",
  "Education",
  "Architecture",
  "Government & Policy",
  "Filmmaking",
].sort();

export const MICRO_NICHES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "AI / ML Engineer",
  "Data Scientist",
  "Data Analyst",
  "DevOps Engineer",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "3D Artist",
  "Director / Filmmaker",
  "Video Editor",
  "Founder / CEO",
  "Product Manager",
  "Venture Capitalist",
  "Investment Banker",
  "Financial Analyst",
  "Growth Marketer",
  "Digital Marketer",
  "SEO Specialist",
  "B2B Sales",
  "Copywriter",
  "Journalist",
  "Physician",
  "Researcher",
  "Professor",
  "Corporate Lawyer",
].sort();

export const RAW_SKILLS = [
  "Python",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "Node.js",
  "Django",
  "Flask",
  "Java",
  "C++",
  "Go",
  "Rust",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Kubernetes",
  "Git",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Computer Vision",
  "NLP",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "Premiere Pro",
  "After Effects",
  "Blender",
  "Unity",
  "Unreal Engine",
  "SEO",
  "SEM",
  "Google Analytics",
  "Copywriting",
  "B2B Sales",
  "Public Speaking",
  "Financial Modeling",
  "Project Management",
  "Agile",
  "Tableau",
  "Power BI",
  "Blockchain",
].sort();

export const LANGUAGES = [
  "English",
  "Hindi",
  "Mandarin",
  "Spanish",
  "French",
  "Arabic",
  "Bengali",
  "Portuguese",
  "German",
  "Japanese",
  "Korean",
  "Tamil",
  "Telugu",
  "Marathi",
  "Turkish",
  "Urdu",
  "Indonesian",
  "Russian",
  "Persian",
];

export const CURRENT_STATUSES = [
  "School Student",
  "Undergraduate Student",
  "Postgraduate Student",
  "Working Professional",
  "Content Creator / Influencer",
  "Freelancer",
  "Dropped Out",
  "Building My Own Thing",
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const COUNTRY_CODES = [
  "+91 🇮🇳",
  "+1 🇺🇸",
  "+44 🇬🇧",
  "+61 🇦🇺",
  "+65 🇸🇬",
  "+971 🇦🇪",
  "+81 🇯🇵",
];
